---

- "Eating from a variety of food groups everyday and you are more likely to obtain all the nutrients essential for your health!"
- "Go for 2 serves of fruit and 5 serves of veg everyday"
- "Eat a variety of fruit and veg and be guided by colour. Choose at least 3 different colours a day. "
- "Bananas contain many key vitamins including B2, B6, and C; also high in dietary fibre, potassium, selenium and magnesium. Great for an energy boost!"
- "Adding garlic to a meal is a good way to add flavour and aroma, without  the concern of calories and salt"
- "Legumes are a great meat alternative. Enjoy a variety, such as chickpeas, kidney beans and lentils"
- "Calcium can be found in foods other than dairy products! For instance sesame seeds, sardines, almonds and broccoli, just to name a few."
- "Obtain adequate dietary fibre everyday (25 – 30g) helps to keep your bowel regular and reduce blood cholesterol"
- "Eat slowly and savour every mouthful of food for satiety and weight control"
- "Watching your weight? Try swapping your salad dressings to balsamic or wine vinegar instead of mayonnaise to avoid consuming the extra energy and saturated fat"
- "Food sources of healthy fats provide energy, fat-soluble vitamins, fatty acids and flavour! Try avocado, nuts & seeds in salads, and cook with olive or canola oil"
- "The type of fat matters! Replace saturated fats from processed foods, with unsaturated fats and omega-3s from fish, nuts and seeds"
- "Opt for mineral water with a squeeze of lemon or lime rather than a normal soft drink - you will be consuming a whopping 40 grams less of refined sugar"
- "Dehydration can often be mistaken for hunger. If unsure, have a glass of water and wait 15 minutes, then ask yourself if you're still hungry"
- "As the days get warmer remember to drink plenty of fluids, especially water, to keep you well hydrated. Aim for 6- 8 glasses a day"
- "Make your own healthier “takeaway” pizza with flat bread, tomato paste, low fat cheese, lean meat and lots of veggies. It saves $ too!"
- "Veggie sticks like carrot, celery and capsicum make great healthy snacks. Keep them in the fridge!"
- "If you’re out and about, dried fruits and nuts can be a convenient alternative to fresh. Portion control is the key, so stick to a handful of 30 grams"
- "Foods with a lower glycemic index (GI) such as whole grains will help keep you feeling satisfied for longer, and reduce the chances of overeating"
- "Choose wholegrain varieties of breads and cereals such as brown rice, wholemeal pasta, quinoa and barley over white or refined varieties - easy ways to increase fibre intake!"
- "A diet that is protein rich with lean meat, fish and eggs with less refined carbs like white bread and sugars helps with weight loss"
- "When eating out, if a meal comes with dressing or sauce, request to serve it on the side so you can control how much to add"
- "Healthy eating habits are important but for optimal health, combine with regular physical activity, relaxation and a healthy social life!"
- "Tips to avoid overeating when dinning out: share a main with a friend, order two entrée dishes, or ask for smaller portions"
- "Take time to do something you enjoy each day, like reading or a hot bath to relieve stress, which keeps you on track with eating healthy"
- "Eating on the run or snacking is common to many but you may eat more kilojoules than you realise! Make time for meals to avoid overeating"
- "Healthy eating starts at shopping! Choose low fat milk, cheese, yoghurt & dressings. Opt for lean, trimmed meat & skinless chicken"
- "Plan healthy, quick and easy meals for busy days"
- "When hungry, fill up with fruit and vegetables"
- "Make meal times special occasions for the whole family, and turn off the TV!"
- "Find a friend or family member to help support you to eat healthy and be active"
- "When eating out, make healthy choices, choose grilled or steamed foods and avoid creamy sauces"
- "Buy fresh produce in season - for better value, availability and quality"
- "Eat at home more often. Try new recipes and invite friends - enjoy good food together!"
- "When the food budget is tight, whole, unprocessed foods can be very economical"
- "Make use of TV ad breaks for exercises, squat, lunge an do push-ups! "
- "Eat regular meals as starving yourself means you’re more likely to overeat at your next meal"
- "Use your hands to guide your portions  – a fist for a healthy serve of potato, rice or pasta; a palm-size for a healthy size of steak, chicken or fish"
